---
- name: Check if pip is already installed
  command: pip3 --version
  ignore_errors: true
  changed_when: false
  register: pip_is_installed

- name: Install pip3
  apt:
    name: python3-pip
    update_cache: yes
  when: pip_is_installed.rc != 0
