---
- name: Install required system packages
  apt: 
    update_cache: yes
    name: 
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-setuptools

- name: install docker if necessary
  raw: test -e /usr/bin/docker || apt install -y docker.io

- name: install docker-dompose if necessary
  raw: test -e /usr/bin/docker-compose || apt install -y docker-compose