---
    - name: Install required system packages
      apt: name={{ item }} update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'software-properties-common', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: "{{ apt_key_url }}"
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker CE
      apt: update_cache=yes name=docker-ce

    - name: Install docker-compose
      get_url: 
        url : "{{ docker_compose_url }}"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'